config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    resources :shopping_lists
  end

  resources :test_recipes
  resources :ingredient_amounts
  resources :ingredients do
    resources :specialty_purchase_destinations
  end
  resources :shopping_list_test_recipes


  root 'pages#show'
end

app/models/test_recipe.rb
class TestRecipe < ApplicationRecord
  has_many :shopping_list_test_recipes, dependent: :destroy
  has_many :shopping_lists, through: :shopping_list_test_recipes
  has_many :ingredient_amounts, dependent: :destroy
  has_many :ingredients, through: :ingredient_amounts

  validates :title, presence: true

  def display_measurements
    self.ingredient_amounts.reduce({}) do |h, measurement|
      h.merge(measurement.id => "#{measurement.amount} #{measurement.units} #{measurement.ingredient.name}")
    end
  end

  def get_ingredient_names(store)
    self.ingredients.map { |ingredient| store[ingredient.name] = [0] }
  end

  def sort_ingredients(store)
    self.ingredient_amounts.each do |process|
      if store[process.ingredient.name]
        store[process.ingredient.name][0] += process.amount
        store[process.ingredient.name][1] = process.units unless store[process.ingredient.name].length > 1
      end
    end
  end
end

app/controllers/test_recipes_controller.rb
class TestRecipesController < ApplicationController
  # before_action :set_shopping_list, :initialize_new_test_recipe, only: [:new, :create]
  before_action :find_and_ensure_test_recipe, except: [:index, :new, :create]

  def index
    @test_recipes = TestRecipe.all
    @my_recipes = current_user.test_recipes
  end

  def new
    @test_recipe = TestRecipe.new
  end

  def create
    test_recipe = TestRecipe.new(test_recipe_params)
    if test_recipe.save
      # if test_recipe.shopping_list_test_recipes.create!(shopping_list_id: params[:shopping_list_id])
        redirect_to test_recipes_path
      # end
    else
      @errors = test_recipe.errors.full_messages
      render 'new'
    end
  end

  def show
    # This recipe has been tried and tested in these lists...
    @measurements = @test_recipe.display_measurements
    @debuted_lists = @test_recipe.shopping_lists.order(shopping_date: :asc)
  end

  def edit
  end

  def update
    if @test_recipe.update(test_recipe_params)
      redirect_to test_recipe_path(@test_recipe)
    else
      @errors = @test_recipe.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    if @test_recipe.destroy
      redirect_to test_recipes_path
    else
      @errors = ['Sorry, unable to process your request.'] # should be flash message
      redirect_to test_recipes_path
    end
  end

  private

  def test_recipe_params
    params.require(:test_recipe).permit(:title)
  end

  def initialize_new_test_recipe
    @test_recipe = TestRecipe.new
  end

  def set_shopping_list
    render 'application/error404' unless @shopping_list = ShoppingList.find_by(id: params[:shopping_list_id])
  end

  def find_and_ensure_test_recipe
    @test_recipe = TestRecipe.find_by(id: params[:id])
  end
end

app/views/test_recipes/_index.html.erb
<div class="cols 12">
  <div class="row">
    <li class="col s6 indv-recipe-title blue-darken-1-text"><%= link_to recipe.title, test_recipe_path(recipe) %></li>
    <li class="col s3">
      <button href="/test_recipes/<%= recipe.id %>" class="btn-floating btn-medium red">
        <input type="hidden" name="_method" value="put" />
        <i class="small material-icons btn-action">edit_mode</i>
      </button>
    </li>
    <li class="col s3">
      <button href="/test_recipes/<%= recipe.id %>" class="btn-floating btn-medium red">
        <input type="hidden" name="_method" value="delete" />
        <i class="small material-icons">delete</i>
      </button>
    </li>
  </div>
</div>

app/views/test_recipes/index.html.erb
 <div class="container">
  <div id="test-recipe-list">
    <h2 class="title-wrapper">Test Recipes</h1>
      <!-- tabbing begins -->
      <div class="row">
        <div class="col s12">
          <ul class="tabs tabs-override">
            <li class="tab col s4"><a class="active" href="#test2">All Recipes</a></li>
            <li class="tab col s4"><a href="#test4">My Recipes</a></li>
          </ul>
        </div>
        <div class="col s12">
          <%= link_to "Add Recipe", new_test_recipe_path, class: "col s2 push-s10 waves-effect waves-light btn #e53935 red darken-1" %>
        </div>
        <!-- tab content begins -->
        <div id="test2" class="col s12">
          <div class="row">
            <% if @test_recipes.any? %>
              <ul>
                <% @test_recipes.each do |recipe| %>
                  <%= render partial: "index", layout: false, locals: { recipe: recipe } %>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
        <div id="test4" class="col s12">
          <div class="row">
            <% if @my_recipes.any? %>
              <ul>
                <% @my_recipes.each do |recipe| %>
                  <%= render partial: "index", layout: false, locals: { recipe: recipe } %>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
        <!-- tab content ends -->
      </div>
    <!-- tabbing ends -->
  </div>
</div>

app/views/test_recipes/new.html.erb
<div id="new-test-recipe-form" class="container">
  <h3 class="center">Test Recipe</h3>
  <div class="row">
    <div class="col s12">
      <%= render partial: 'application/errors', layout: false, locals: { errors: @errors } %>
    </div>
  </div>
  <div class="row">
    <div class="col s10 offset-s1">
      <%= form_for :test_recipe, url: test_recipes_path do |f| %>
      <div class="row">
        <div class="col s6 offset-s2" id="test-recipe-title-input">
          Title: <%= f.text_field :title %>
        </div>
      </div>
    <div class="row create-new-test-recipe-btn">
      <div class="center" id="create-new-test-recipe-btn">
        <%= f.submit "Submit", :class => "waves-effect waves-light btn #e53935 red darken-1" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/test_recipes/show.html.erb
<div class="container">
  <div id="test-recipe-display">
    <h2 class="title-wrapper"><%= @test_recipe.title %></h1>
      <div class="cols 12">
        <div class="row">
          <table>
             <thead>
               <tr>
               </tr>
             </thead>
             <% if @measurements.any? %>
             <tbody>
               <% @measurements.each do | amount_id, measurement | %>
               <tr>
                 <td><%= link_to measurement, ingredient_amount_path(amount_id), class: "black-text" %></td>
                 <td>
                   <button href="/ingredient_amounts/<%= amount_id %>/edit" class="btn-floating btn-medium red">
                      <input type="hidden" name="_method" value="put" />
                      <i class="small material-icons btn-action">edit_mode</i>
                    </button>
                  </td>
                 <td>
                    <button href="/ingredient_amounts/<%= amount_id %>" class="btn-floating btn-medium red">
                      <input type="hidden" name="_method" value="delete" />
                      <i class="small material-icons">delete</i>
                    </button>
                  </td>
               </tr>
               <% end %>
             </tbody>
           </table>
          </div>
        </div>
      <% end %>
      <p>
        <%= link_to "Add Ingredient", new_ingredient_amount_path(test_recipe_id: @test_recipe.id), :class => "waves-effect waves-light btn #e53935 red darken-1" %>
      </p>
    </div>
  </div>