config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    resources :shopping_lists
  end

  resources :test_recipes
  resources :ingredient_amounts
  resources :ingredients do
    resources :specialty_purchase_destinations
  end
  resources :shopping_list_test_recipes


  root 'pages#show'
end

app/models/ingredient_amount.rb
class IngredientAmount < ApplicationRecord
  belongs_to :test_recipe
  belongs_to :ingredient

  validates :units, :amount, :test_recipe_id, :ingredient_id, presence: true
end

app/controllers/ingredient_amounts_controller.rb
class IngredientAmountsController < ApplicationController
  def new
    @units = ['Bunch', 'Tbsp', 'Tsp', 'Each', 'Grams']
    @test_recipe = TestRecipe.find_by(id: params[:test_recipe_id])
    @ingredients = Ingredient.all.order(name: :asc)
    @ingredient_amount = IngredientAmount.new
  end

  def create
    measurement = IngredientAmount.new(ingredient_amount_params)
    if measurement.save
      redirect_to test_recipe_path(@test_recipe)
    else
      @errors = ingredient_amount.errors.full_messages
      render 'new'
    end
  end

  def edit
    @ingredient_amount = IngredientAmount.find_by(id: params[:id])
    @test_recipe = @ingredient_amount.test_recipe
    @ingredients = Ingredient.all.order(name: :asc)
  end

  def update
    @ingredient_amount = IngredientAmount.find_by(id: params[:id])
    if @ingredient_amount.update(ingredient_amount_params)
      redirect_to test_recipe_path(@ingredient_amount.test_recipe)
    else
      @errors = @ingredient_amount.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @ingredient_amount = IngredientAmount.find_by(id: params[:id])
    @test_recipe = @ingredient_amount.test_recipe # in case of  failure to delete
    @debuted_lists = @test_recipe.shopping_lists.order(shopping_date: :asc)
    if @ingredient_amount.destroy
      redirect_to test_recipe_path(@test_recipe) ## @ingredient_amount may or may not be null
      # in which case, create variable test_recipe = @ingredient_amount.test_recipe before destroy
    else
      @errors = ['Sorry, unable to process your request.']
      render 'test_recipes/show'
    end
  end

  private

  def ingredient_amount_params
    params.require(:ingredient_amount).permit(:amount, :units, :test_recipe_id, :ingredient_id)
  end
end

app/views/ingredient_amounts/new.html.erb
<div id="ingredient-amount-form" class="container">
  <h1 class="center">Ingredient Amount</h1>
  <div class="row">
    <div class="col s12">
      <%= render partial: 'application/errors', layout: false, locals: { errors: @errors } %>
    </div>
  </div>
  <div class="row">
    <div class="col s10 offset-s1">
      <%= form_for :ingredient_amount, url: ingredient_amounts_path do |f| %>
      <div class="row">
        <div class="col s6 offset-s2">
          Amount: <%= f.number_field :amount %>
        </div>
        <div class="col s6 offset-s2">
          Recipe: <%= f.select(:test_recipe_id, options_for_select([[@test_recipe.title, @test_recipe.id]])) %>
        </div>
      </div>
      <div class="row">
        <div class="col s6 offset-s2">
          <% ingredients_array = @ingredients.map { |ingredient| [ingredient.name, ingredient.id] } %>
          Ingredient: <%= f.select(:ingredient_id, options_for_select(ingredients_array)) %>
        </div>
        <div class="col s6 offset-s2">
          Unit: <%= f.select :units, @units.map { |unit| unit } %>
        </div>
      </div>
    <div class="row create-new-shopping-list-btn">
      <div class="center" id="create-new-shopping-list-btn">
        <%= f.submit "Submit", :class => "waves-effect waves-light btn #e53935 red darken-1" %>
      </div>
    </div>
    <% end %>
  </div>
</div>