config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    resources :shopping_lists
  end

  resources :test_recipes
  resources :ingredient_amounts
  resources :ingredients do
    resources :specialty_purchase_destinations
  end
  resources :shopping_list_test_recipes


  root 'pages#show'
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  has_many :shopping_list_test_recipes, dependent: :destroy
  has_many :test_recipes, through: :shopping_list_test_recipes

  validates :title, :shopping_date, :user_id, presence: true

  def display_shopping_date
    self.shopping_date.strftime('%m/%d/%Y')
  end
  
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :find_and_ensure_shopping_list, except: [:index, :new, :create]
  before_action :initialize_new_shopping_list, only: [:new, :create]

  def index
    # binding.pry
    @shopping_lists = current_user.shopping_lists
    @past_lists = current_user.shopping_lists.where('shopping_date < ?', DateTime.now)
  end

  def new
  end

  def create
    shopping_list = current_user.shopping_lists.new(shopping_list_params)
    if shopping_list.save
      redirect_to user_shopping_list_path(current_user, shopping_list)
    else
      @errors = shopping_list.errors.full_messages
       render 'new'
    end
  end

  def show
    # binding.pry
    @test_recipes = @shopping_list.test_recipes
    @ingredients = {}
    @test_recipes.each do |recipe|
      recipe.get_ingredient_names(@ingredients)
    end
    @test_recipes.each do |recipe|
      recipe.sort_ingredients(@ingredients)
    end
    @test_recipes
  end

  def edit
  end

  def update
    if @shopping_list.update(shopping_list_params)
      redirect_to shopping_list_path(@shopping_list)
    else
      @errors = @shopping_list.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    if @shopping_list.destroy
      redirect_to shopping_list_index   ## correct this
    else
      @errors = ['Unable to process your request. Please try again.']
      render 'show' ## OR maybe render 'edit'??
    end
  end

  private

  def shopping_list_params
    params.require(:shopping_list).permit(:title, :shopping_date, :user_id)
  end

  def find_and_ensure_shopping_list
    render 'application/error404' unless @shopping_list = ShoppingList.find_by(id: params[:id])
  end

  def initialize_new_shopping_list
    @shopping_list = ShoppingList.new
  end
end

app/views/shopping_lists/_index.html.erb
<ul>
  <% @shopping_lists.each do |list| %>
    <li><a href='/users/<%= current_user.id %>/shopping_lists/<%= list.id %>' data='{shopping_list_id: <%= list.id %>}'><%= list.title %></a></li>
    <li>Intended Date: <%= list.display_shopping_date %></li>
  <% end %>
</ul>

app/views/shopping_lists/_shopping_list.html.erb
<div class="cols 12">
  <div class="row">
    <li class="col s3 indv-recipe-title blue-darken-1-text"><%= link_to list.title, user_shopping_list_path(current_user, list.id) %><br>
    Expected Shopping Date: <%= list.display_shopping_date %>
    </li>
    <!-- <li class="col s3 indv-recipe-title blue-darken-1-text">Expected Shopping Date: <%= list.display_shopping_date %></li> -->
    <li class="col s3">
      <button href="/users/<%= current_user.id %>/shopping_lists/<%= list.id %>/edit" class="btn-floating btn-medium red">
        <input type="hidden" name="_method" value="put" />
        <i class="small material-icons btn-action">edit_mode</i>
      </button>
    </li>
    <li class="col s3">
      <button href="/users/<%= current_user.id %>/shopping_lists/<%= list.id %>" class="btn-floating btn-medium red">
        <input type="hidden" name="_method" value="delete" />
        <i class="small material-icons">delete</i>
      </button>
    </li>
  </div>
</div>

app/views/shopping_lists/index.html.erb
<div class="container">
 <div id="shopping-list-display">
   <h3 class="title-wrapper">My Shopping Lists</h3>
     <!-- tabbing begins -->
     <div class="row">
       <div class="col s12">
         <ul class="tabs tabs-override">
           <li class="tab col s4"><a class="active" href="#test2">Upcoming Trips</a></li>
           <li class="tab col s4"><a href="#test4">Past Lists</a></li>
         </ul>
       </div>
       <div class="col s12">
         <%= link_to "Add List", new_user_shopping_list_path(current_user), class: "col s2 push-s10 waves-effect waves-light btn #e53935 red darken-1" %>
       </div>
       <!-- tab content begins -->
       <div id="test2" class="col s12">
         <div class="row">
           <% if @shopping_lists.any? %>
             <ul>
               <% @shopping_lists.each do |list| %>
                 <%= render partial: "shopping_list", layout: false, locals: { list: list } %>
               <% end %>
             </ul>
           <% end %>
         </div>
       </div>
       <div id="test4" class="col s12">
         <div class="row">
           <% if @past_lists.any? %>
             <ul>
               <% @past_lists.each do |list| %>
                 <%= render partial: "shopping_list", layout: false, locals: { list: list } %>
               <% end %>
             </ul>
           <% else %>
            <p>No Past Lists<p>
           <% end %>
         </div>
       </div>
       <!-- tab content ends -->
     </div>
   <!-- tabbing ends -->
 </div>
</div>

app/views/shopping_lists/new.html.erb
<div id="new-shopping-list-form" class="container">
  <h1 class="center">New Shopping List</h1>
  <div class="row">
    <div class="col s12">
      <%= render partial: 'application/errors', layout: false, locals: { errors: @errors } %>
    </div>
  </div>
  <div class="row">
    <div class="col s10 offset-s1">
      <%= form_for :shopping_list, url: user_shopping_lists_path(current_user) do |f| %>
      <div class="row">
        <div class="col s6 offset-s2">
          Title: <%= f.text_field :title %>
        </div>
      </div>
      <div class="row">
        <div class="col s4 offset-s2">
          Expected Shopping Date:
        <input type="date" class="datepicker" name="shopping_list[shopping_date]">
        </div>
      </div>
    <div class="row create-new-shopping-list-btn">
      <div class="center" id="create-new-shopping-list-btn">
        <%= f.submit "Submit", :class => "waves-effect waves-light btn #e53935 red darken-1" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shopping_lists/show.html.erb
<div class="container">
  <div id="shopping-list-display">
    <h2 class="title-wrapper"><%= @shopping_list.title %></h1>
    <!-- tabbing begins -->
      <div class="row">
        <div class="col s12">
          <ul class="tabs tabs-override">
            <li class="tab col s4"><a class="active" href="#test2">All Recipes</a></li>
            <li class="tab col s4"><a href="#test4">Item Totals</a></li>
          </ul>
        </div>
        <div class="col s12">
          <%= link_to "Add Recipe", new_test_recipe_path, class: "col s2 push-s10 waves-effect waves-light btn #e53935 red darken-1 new-recipe-btn" %>
        </div>

        <div class="col s12">
          <%= link_to "Create Recipe", new_shopping_list_test_recipe_path(shopping_list_id: @shopping_list.id), class: "col s2 push-s10 waves-effect waves-light btn #e53935 red darken-1 new-recipe-btn" %>
        </div>
        <!-- tab content begins -->
        <div id="test2" class="col s12">
          <div class="row">
            <% if @test_recipes.any? %>
              <ul>
                <% @test_recipes.each do |recipe| %>
                  <%= render partial: "test_recipes/index", layout: false, locals: { recipe: recipe } %>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
        <div id="test4" class="col s12">
          <div class="row">
            <h5>Ingredient Totals</h5>
            <% if @ingredients.any? %>
              <ul>
                <% @ingredients.each do |ingredient, count| %>
                  <li><%= count.first %> <%= count.last %> of <%= ingredient %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
      <!-- tab content ends -->
  </div>
</div>

app/views/shopping_lists/sub.html.erb
<h1>My Shopping Lists</h1>

<% if @shopping_lists.any? %>
  <%= render partial: 'index', locals: { shopping_lists: @shopping_lists }, layout: false %>
<% else %>
  <p>You haven't created any shopping lists. <%= link_to 'Start one here!', new_user_shopping_list_path(current_user) %></p>
<% end %>