config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    resources :shopping_lists
  end

  resources :test_recipes
  resources :ingredient_amounts
  resources :ingredients do
    resources :specialty_purchase_destinations
  end
  resources :shopping_list_test_recipes


  root 'pages#show'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceryList</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>

    <div class="">
      <nav>
        <div class="nav-wrapper">
          <a href="/" class="brand-logo title-wrapper">GroceryList</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if logged_in? %>
              <li><%= link_to current_user.username, user_path(current_user) %></li>
              <li><%= link_to "Log Out", session_path(current_user), method: :delete %></li>
            <% else %>
              <li><%= link_to "Log In", new_session_path%></li>
              <li><%= link_to "Sign Up", new_user_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    </div>
    <% if logged_in? %>
      <ul id="slide-out" class="side-nav fixed">

          <li>
            <img src="https://cdn0.iconfinder.com/data/icons/shopping-41/70/groceries-512.png" class="circle responsive-img side-nav-greeting-img homepage-img">
          <li>
          <li><div class="divider"></div><li>
          <li><%= link_to "Test Recipes", test_recipes_path %></li>
          <li><%= link_to "Shopping Lists", user_shopping_lists_path(current_user)%></li>
          <li><%= link_to "Ingredients", ingredients_path %></li>
      </ul>
    <% end %>

    <main>
    <%= yield %>
    </main>
    <footer class='center page-footer white-text'>
      &copy;GroceryList &#8226; A Plated Intern Project By:
      <a href='https://github.com/catkhuu' class='white-text' id='footer-github-link'>Catherine Khuu</a>
    </footer>
  </body>
</html>